### ISSUE TITLE
[Kibana] Typo in the latest framework

### ISSUE THREAD

**Issue by srajappa** [mesosphere/universe#2562] opened 2020-09-08 19:56 UTC
## Description
`kibana_framework_version: 2.7.0-6.8.2`

On deploying Kibana on DC/OS we get the following error
```
sh: 1: ./init.sh: Permission denied
```
On further inspection we saw a typo in the file `resource.json` [file](https://github.com/mesosphere/universe/blob/version-3.x/repo/packages/K/kibana/1200/resource.json#L5-L6). If one could observe, the values of the keys have been interchanged. 

```
"init-sh": "https://downloads.mesosphere.com/kibana/assets/2.7.0-6.8.2/nginx.conf.tmpl",
"nginx-conf-tmpl": "https://downloads.mesosphere.com/kibana/assets/2.7.0-6.8.2/init.sh"
```
Changing the values for the keys should solve the problem above because `nginx-conf-tmpl` when fetched doesn't make the file (in this case **init.sh**) executable.

**Comment by rishabh96b** [comment] 2020-09-15 12:55
Thanks for reporting this @srajappa . This seems to have caused by an issue in our build job. I will push a fix for this issue.

**Closed as completed** 2020-09-16 12:17 UTC
